### ISSUE TITLE
Wrong UID/GID evaluation logic in entrypoint script (proftpd.sh)

### ISSUE THREAD

**Issue by gschafra** [MekayelAnik/proftpd-server-alpine#1]
In the per share user/group creation part due to a probably unintentional logical check (see test-image-builder/proftpd.sh#L26](https://github.com/MekayelAnik/proftpd-server-alpine/blob/main/test-image-builder/proftpd.sh#L26, `||` instead of `&&`), the following if conditions (either only `FTP_SHARE_${i}_PUID` or `FTP_SHARE_${i}_GUID` is not given) will be never reached.

In my case, I want to set a fixed PGID per user/share (`FTP_SHARE_${i}_PGID`) but let the the user ID be generated automatically, which will be handled in https://github.com/MekayelAnik/proftpd-server-alpine/blob/main/test-image-builder/proftpd.sh#L31, but which will be never reached because of the problem.

**Comment by MekayelAnik** [comment]
@gschafra can you please elaborate, what you are trying to achieve by doing so?
I didn't understand the issues you are facing.

**Comment by gschafra** [comment]
@MekayelAnik I wanna do something like this (let the PUIDs be generated automatically but provide the PGIDs):
```yaml
    ftpserver:
        image: mekayelanik/proftpd-server-alpine:latest
        ports:
            - "21:21"
        environment:
            - TZ=Europe/Berlin
            - FTP_PORT=21
            - NUMBER_OF_SHARES=2
            - FTP_SHARE_1=kd209974-10
            - FTP_SHARE_1_PGID=1231
            - FTP_PASSWORD_1=XXXXXXX
            - FTP_SHARE_2=kd209974-11
            - FTP_SHARE_2_PGID=1341
            - FTP_PASSWORD_2=XXXXXXX
```

Please take a look at my PR #2, it,s pretty obvious where the problem lies. The part of the script, which is responsible for the user and group creation if NO FTP_SHARE_{1}_PUID is given (`elif [ -z "${!FTP_UID}" ] ; then`, https://github.com/MekayelAnik/proftpd-server-alpine/blob/main/test-image-builder/proftpd.sh#L31-L34) is NEVER reached since in https://github.com/MekayelAnik/proftpd-server-alpine/blob/main/test-image-builder/proftpd.sh#L26 (`[ -z "${!FTP_UID}" ] || [ -z "${!FTP_GID}" ]`) is also true in this case (because it is an OR logic, means if `FTP_UID` OR `FTP_UID` is empty). I think the intention of https://github.com/MekayelAnik/proftpd-server-alpine/blob/main/test-image-builder/proftpd.sh#L26-L30 should be to "catch" the case, that BOTH `FTP_UID` AND `FTP_UID` are empty, shouldn't it?
